---
meta:  
  author: isux
  homepage: http://isux.tencent.com
  email: isux@qq.com
  twitter: http://t.qq.com/isux
  github: https://github.com/isux/aoi.font
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

#transform:
#  baseline: 0.4
#  rescale: 2.4

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: aoi

  fullname: aoi
  familyname: aoi

  copyright: Copyright (C) 2013 by isux qzone team

  ascent: 850
  descent: 150
  weight: Normal


glyphs:

  -
    css: activity
    code: 0xf800
    uid: d97f2667f3da0845da7baaeda485e2da 
    meta:
      author: isux
      email: isux@qq.com
    search: [activity]
  -
    css: app-add
    code: 0xf861
    uid: 3aa86a7bb0229b2a681f39ae7a2441a6 
    meta:
      author: isux
      email: isux@qq.com
    search: [app]
  -
    css: app-center
    code: 0xf862
    uid: f220a344361b32db28c66048168faf9c 
    meta:
      author: isux
      email: isux@qq.com
    search: [app, center]
  -
    css: arrow-top
    code: 0xf863
    uid: ec94ff56b8332bd3edc3a4e90e7749e7 
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow, top]
  -
    css: board
    code: 0xf864
    uid: ed99f7b52ba602f0ca3c4f0c2e0c5093 
    meta:
      author: isux
      email: isux@qq.com
    search: [board]
  -
    css: cert
    code: 0xf865
    uid: f6474f6853e2276e536c8993268d5fca 
    meta:
      author: isux
      email: isux@qq.com
    search: [cert]
  -
    css: cloudy
    code: 0xf866
    uid: 7ce2e72d9618a8fbf8a48929b7a21129 
    meta:
      author: isux
      email: isux@qq.com
    search: [cloudy, weather]
  -
    css: dress
    code: 0xf867
    uid: b7456e47f7f5b65b43002ca73aa24978 
    meta:
      author: isux
      email: isux@qq.com
    search: [dress]
  -
    css: gift
    code: 0xf868
    uid: d3f8eb91dea871ad107fc0360b9ff171 
    meta:
      author: isux
      email: isux@qq.com
    search: [gift]
  -
    css: homepage
    code: 0xf869
    uid: b7e2aee962ff7c39b5c86eca087af247 
    meta:
      author: isux
      email: isux@qq.com
    search: [homepage]
  -
    css: zan
    code: 0xf871
    uid: 0e74d2ca29545fa136f86b624f14ea0e 
    meta:
      author: isux
      email: isux@qq.com
    search: [zan, like]
  -
    css: zan2
    code: 0xf870
    uid: 9d42e2e7585e0095e9e187e0bec2e2b2 
    meta:
      author: isux
      email: isux@qq.com
    search: [like, zan]
  -
    css: list-more
    code: 0xf872
    uid: e0b38208d9d176a230ed13b9cd67ba03 
    meta:
      author: isux
      email: isux@qq.com
    search: [list, more]
  -
    css: love
    code: 0xf873
    uid: ca067dd82971bf903278a81a3d227f1d 
    meta:
      author: isux
      email: isux@qq.com
    search: [love]
  -
    css: mail
    code: 0xf874
    uid: 12b380d0d2ab84c3247554a38e16cf9e 
    meta:
      author: isux
      email: isux@qq.com
    search: [mail]
  -
    css: myhome
    code: 0xf875
    uid: a136da43c30d3c8e34b5b328dec920e1 
    meta:
      author: isux
      email: isux@qq.com
    search: [myhome, home]
  -
    css: pengyou
    code: 0xf876
    uid: cb6c4d8bde4e9338951335c202118b68 
    meta:
      author: isux
      email: isux@qq.com
    search: [pengyou,logo,tencent]
  -
    css: search
    code: 0xf877
    uid: 55c6cc587abf8016c88193a1b20cdb27 
    meta:
      author: isux
      email: isux@qq.com
    search: [search]
  -
    css: weibo
    code: 0xf878
    uid: 020ae88a09a73581333c657b79d0e4c6 
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo,tencent]
